anime/urls.py
from django.urls import path
from . import views

app_name = 'anime'

urlpatterns = [
    path('', views.home, name='home'),
    path('get_anime/<str:name>', views.get_anime, name='get_anime'),
    path('getdata/', views.get_data, name='get_data'),
    path('getanime/', views.get_anime, name='get_anime'),
    path('search', views.search, name='search'),
]

animeproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('anime.urls', namespace='anime')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

anime/models.py
from django.db import models

# Create your models here.

anime/views.py
from django.http import HttpResponse, JsonResponse
from AnilistPython import Anilist
from django.shortcuts import render

def get_anime(request,name):
    anilist = Anilist()
    ani_list = anilist.get_anime(name)
    return JsonResponse(ani_list)

def get_data(request):
    if request.method != 'POST':
        return HttpResponse(status=400)
    anilist = Anilist()
    t=request.POST.get('type')
    search=request.POST.get('search')
    if t=='anime':
        data=anilist.get_anime(search)
    elif t=='manga':
        data=anilist.get_manga(search)
    elif t=='character':
        data=anilist.get_character(search)
    else:
        data={'error':'Invalid Type'}
        return JsonResponse(data,status=400)
    data['type']=t
    return JsonResponse(data,status=200)

def home(request):
    return render(request, 'anime/home.html')


def search(request):
    return render(request, 'anime/search.html')

def get_anime(request):
    if request.method != 'POST':
        return HttpResponse(status=400)
    # print(request.POST)
    anilist = Anilist()
    geners=request.POST.getlist('genres[]')
    years=[int(a) for a in request.POST.getlist('years[]')]
    rating_start=int(request.POST.get('rating[start]'))
    rating_end=int(request.POST.get('rating[end]'))
    if 1944 in years:
        years.remove(1944)
    # print(geners,years,rating_start,type(rating_end),sep='\n')
    if rating_start==0 and rating_end==100:
        data = anilist.search_anime(genre=geners, year=years)
    if rating_start<0 or rating_end>100 or rating_start>rating_end:
        return JsonResponse({'error':'Invalid Rating'},status=400)
    data = anilist.search_anime(genre=geners, year=years, score=range(rating_start, rating_end+1))
    data = {'anime':data}
    return JsonResponse(data)

anime/templates/anime/home.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'anime/home.css' %}" />
{% endblock %} {% block content %}
<div class="outer-container">
  <div class="container">
    {% csrf_token %}
    <div class="inner-container">
      <input type="search" placeholder="Search" id="search" onfocus="hideResult()"/>
      <div class="radio-buttons">
        <span>
          <input type="radio" id="anime" name="type" value="anime" checked />
          <label for="anime">Anime</label>
        </span>
        <span>
          <input type="radio" id="manga" name="type" value="manga" />
          <label for="manga">Manga</label>
        </span>
        <span>
          <input type="radio" id="character" name="type" value="character" />
          <label for="character">Character</label>
        </span>
      </div>
      <a href="{% url 'anime:search' %}" class="filter-search">Search Anime's by filters</a>
    </div>
  </div>
  <div class="holder" id="holder">
    <img src="" class="banner" id="banner" alt="" />
    <div class="card-cover">
      <div class="card">
        <img src="" id="cover" alt="" />
      </div>
      <div class="info">
        <div class="top-info">
          <h1 id="title"></h1>
          <div id="date">
            <span id="start-date"></span>
            <span id="end-date"></span>
          </div>
        </div>
        <p id="description"></p>
        <div class="info-container" id="info-container">
          <div class="info-box">
            <h3>Rating:</h3>
            <h3 id="rating"></h3>
          </div>
        </div>
      </div>
    </div>
  </div>
  

</div>
{% endblock %}
 {% block scripts %}
  <script type="text/javascript" src="{% static 'anime/home.js' %}"></script>
{% endblock %}

anime/templates/anime/search.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'anime/search.css' %}" />
{% endblock %} {% block content %}
<div class="search-holder-container">
<div class="filter-outer">
<div class="filter-container">
    <div class="row">
        <div class="year-container">
            <div>Year: </div>
            <div class="year">
                <input name="startYear" id="startYear" class="date-picker-year year-field" value="1924" min="1924"/>
                <div>to</div>
                <input name="startYear" id="endYear" class="date-picker-year year-field" value="2023"/>
            </div>
        </div>
        <div class="rating-container">
            <div>Rating: </div>
            <div class="rating">
                <input id="startRating" type="number" max="100" min="0" value="0">
                <div>to</div>
                <input id="endRating" type="number" max="100" min="0" value="100">
            </div>
        </div>
    </div>
    <div class="row">
        <input type="search" id="search_genres" placeholder="Add Genre">
        <div id="suggestionBox" style="display: none;"></div>
        <div class="button" onclick="get_data()">Search</div>
    </div>
    <div class="row">
        <div class="genre-outer-container">
        <div class="genre-container" id="genre-container">No genres selected</div>
        </div>
    </div>
</div>
</div>
<div class="result-outer-container">
    <div class="result-container" id="result-container">
    </div>
</div>
</div>

<div class="display-container" id="display-container">
    <div class="display-inner-container">
    <img id="back_button" src="media/back_icon.png" alt="back button" onclick="closeAnimeBox()">
    <div class="anime-cover-container" id="anime-cover-container"><img class="anime-cover" id="anime_cover" src="" ></img></div>
    <h3 class="anime-title" id="anime_title"></h3>
    <div class="row">
        <img src="" alt="" class="left-image" id="left_image">
        <div class="info-box right-box">
            <div class="anime-description" id="anime_description">
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript" src="{% static 'anime/search.js' %}"></script>
{% endblock %}

anime/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AniInfo</title>
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <script type="text/javascript" src="{% static 'jquery-3.7.1.min.js' %}"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    
    {% block head %}
    {% endblock head %}
</head>
<body>
    <nav class="navbar">
        <div class="header">AniInfo</div>
    </nav>
    {% block content %}
    {% endblock content %}
    <div class="loading">
        <div class="loadingWrapper">
          <div id="loading"> </div>
          <h1 class="load-text">Loading . . .</h1>
        </div>
      </div>
    
    <script type="text/javascript" src="{% static 'base.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
</body>
</html>